# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cargapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cargapp

  target 'CargappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Cargapp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cargapp-tvOS

  target 'Cargapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
